### ISSUE TITLE
Relational data

### ISSUE THREAD

**Issue by arnespremberg** [rjjakes/wordpress-orm#3]
Hi!!

Thanks for your wonderful package! It helps me a lot while working on some plugins.
I was just wondering how the status is with relational data?

I found these properties
``@ORM_ManyToOne \Symlink\ORM\Models\Users
   @ORM_JoinProperty ID``
But that's basically it. I can't get them to work, and I don't really understand how they're implemented.

If you were to provide me with some information about the implementation, I'll be glad to contribute to the repo!

All the best,
Arne

**Comment by rjjakes** [comment]
Hi Arne, 
I haven't done any work on joining so you are free to implement this however you wish and raise a PR.

**Comment by arnespremberg** [comment]
Hey!
Alright. I have already forked the repo and will possibly start implementing the functions for my current project. If they will be generally usable I’ll raise a PR.
Am 23. März 2020, 18:37 +0100 schrieb rjjakes <notifications@github.com>:
