### ISSUE TITLE
Implementation of post meta table

### ISSUE THREAD

**Issue by joworeiter** [rjjakes/wordpress-orm#8]
Hi there, 
I was wondering if I could offer a Pull Request for the post meta table. But before I would like your opinion on how to implement it. 
In a project of mine I did a quick implementation with a trait of BaseModel Class since post_meta doest has an ID column and so it would throw ab error. Eventhough this works, I was wondering if it's not better to create a new abstract class, which contains the Id, so that there is more flexibility on creating own tables. 
Thanks for your feedback!

**Comment by rjjakes** [comment]
> I was wondering if it's not better to create a new abstract class, which contains the Id, so that there is more flexibility on creating own tables.

I think this is a good idea @joworeiter

**Comment by joworeiter** [comment]
#9 Pull Request is here!

**Comment by rjjakes** [comment]
I've merged your PR to master
